name: Build website

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'

  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - '*.md'
      - '*.txt'
    types: [ opened, synchronize, reopened ]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'


      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml -DskipTests -DskipITs

      - name: Validate generated documentation
        run: |
          STATUS=$(git status --porcelain docs/modules/ROOT/pages/includes/)
          if [ -n "$STATUS" ]; then
            echo -e "Generated documentation is not up to date."
            echo ""
            echo "The following generated files were changed or added and must be committed:"
            echo ""
            echo "$STATUS" | sed 's/^?? / /; s/^ M / /; s/^/* /'
            echo ""
            echo "To fix this:"
            echo "  1. Run: mvn clean install"
            echo "  2. Commit the generated documentation files"
            exit 1
          else
            echo -e "Generated documentation is up to date."
          fi


      - name: Store PR id
        run: |
          mkdir pr
          echo ${{ github.event.number }} > ./pr/pr-id.txt

      - name: Upload PR id as artifact
        uses: actions/upload-artifact@v6
        with:
          name: pr-id
          path: pr
          retention-days: 1

      - name: Publishing directory for PR preview
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: site
          path: ./docs/target/classes/META-INF/resources/antora
          retention-days: 3
